name: lyell
description: Generator utilities used by darwin and dogs..
version: 1.5.0
repository: https://github.com/DarwinFramework/lyell

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
