name: lyell_gen
description: Generator utilities used by darwin and dogs.
version: 3.0.12
repository: https://github.com/DarwinFramework/lyell

environment:
  sdk: '>=3.5.0 <4.0.0'

resolution: workspace

dependencies:
  build: ^4.0.4
  analyzer: ^10.0.2
  source_gen: ^4.2.0
  crypto: ^3.0.7
  glob: ^2.1.3
  path: ^1.9.1
  code_builder: ^4.11.1
  dart_style: ^3.1.5
  collection: ^1.19.1

  lyell: ^1.4.6
  mutex: ^3.1.0
  duffer: ^2.3.2
dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
