name: generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^4.0.4
  analyzer: ^10.0.2
  source_gen: ^4.2.0
  crypto: ^3.0.7
  glob: ^2.1.3
  path: ^1.9.1
  code_builder: ^4.11.1
  dart_style: ^3.1.5
  collection: ^1.19.1

  lyell: any
  lyell_gen: any

dev_dependencies:
  lints: ^6.1.0
