name: implementation
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.9.1
  lyell: any

dev_dependencies:
  build_runner: any
  generator:
    path: ../generator
  lints: ^6.1.0
  test: ^1.21.0